language: node_js
cache: npm
jobs:
  include:
    - stage: deploy
      before_script: npm i -g now
      script: now --target production --token=$NOW_TOKEN
stages:
  - test
  - name: deploy
    if: branch = master